// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBydiKcJqNm1yky2lLOtsonpYLp8hBGYoA',
    appId: '1:902325669003:web:69a6114ed272713ce6588e',
    messagingSenderId: '902325669003',
    projectId: 'vodth-dapp',
    authDomain: 'vodth-dapp.firebaseapp.com',
    databaseURL: 'https://vodth-dapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vodth-dapp.appspot.com',
    measurementId: 'G-NENL551MPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN2Xt7WPsImJ3llDoeu97ksqgeXTgMLkI',
    appId: '1:902325669003:android:3f990442820855a5e6588e',
    messagingSenderId: '902325669003',
    projectId: 'vodth-dapp',
    databaseURL: 'https://vodth-dapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vodth-dapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBX04nC5pxggbXRqqeXKUNCoxRKAA7eHw',
    appId: '1:902325669003:ios:ed48fb58d4803681e6588e',
    messagingSenderId: '902325669003',
    projectId: 'vodth-dapp',
    databaseURL: 'https://vodth-dapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vodth-dapp.appspot.com',
    iosBundleId: 'com.example.vodthMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBX04nC5pxggbXRqqeXKUNCoxRKAA7eHw',
    appId: '1:902325669003:ios:ed48fb58d4803681e6588e',
    messagingSenderId: '902325669003',
    projectId: 'vodth-dapp',
    databaseURL: 'https://vodth-dapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vodth-dapp.appspot.com',
    iosBundleId: 'com.example.vodthMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBydiKcJqNm1yky2lLOtsonpYLp8hBGYoA',
    appId: '1:902325669003:web:cde72d9327fd96a4e6588e',
    messagingSenderId: '902325669003',
    projectId: 'vodth-dapp',
    authDomain: 'vodth-dapp.firebaseapp.com',
    databaseURL: 'https://vodth-dapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vodth-dapp.appspot.com',
    measurementId: 'G-X0TXCZHJRB',
  );

}